/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ProcessosIndexRouteImport } from './routes/processos.index'
import { Route as ProcessosProcessoIdRouteImport } from './routes/processos.$processoId'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios.index'
import { Route as RelatoriosRelatorioIdRouteImport } from './routes/relatorios.$relatorioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIndexRoute = ProcessosIndexRouteImport.update({
  id: '/processos/',
  path: '/processos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosProcessoIdRoute = ProcessosProcessoIdRouteImport.update({
  id: '/processos/$processoId',
  path: '/processos/$processoId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRelatorioIdRoute = RelatoriosRelatorioIdRouteImport.update({
  id: '/relatorios/$relatorioId',
  path: '/relatorios/$relatorioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/painel': typeof PainelRoute
  '/usuarios': typeof UsuariosRoute
  '/processos/$processoId': typeof ProcessosProcessoIdRoute
  '/relatorios/$relatorioId': typeof RelatoriosRelatorioIdRoute
  '/processos/': typeof ProcessosIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/painel': typeof PainelRoute
  '/usuarios': typeof UsuariosRoute
  '/processos/$processoId': typeof ProcessosProcessoIdRoute
  '/relatorios/$relatorioId': typeof RelatoriosRelatorioIdRoute
  '/processos': typeof ProcessosIndexRoute
  '/relatorios': typeof RelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/painel': typeof PainelRoute
  '/usuarios': typeof UsuariosRoute
  '/processos/$processoId': typeof ProcessosProcessoIdRoute
  '/relatorios/$relatorioId': typeof RelatoriosRelatorioIdRoute
  '/processos/': typeof ProcessosIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/documentos'
    | '/painel'
    | '/usuarios'
    | '/processos/$processoId'
    | '/relatorios/$relatorioId'
    | '/processos/'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/documentos'
    | '/painel'
    | '/usuarios'
    | '/processos/$processoId'
    | '/relatorios/$relatorioId'
    | '/processos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/documentos'
    | '/painel'
    | '/usuarios'
    | '/processos/$processoId'
    | '/relatorios/$relatorioId'
    | '/processos/'
    | '/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentosRoute: typeof DocumentosRoute
  PainelRoute: typeof PainelRoute
  UsuariosRoute: typeof UsuariosRoute
  ProcessosProcessoIdRoute: typeof ProcessosProcessoIdRoute
  RelatoriosRelatorioIdRoute: typeof RelatoriosRelatorioIdRoute
  ProcessosIndexRoute: typeof ProcessosIndexRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/': {
      id: '/processos/'
      path: '/processos'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProcessosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/$processoId': {
      id: '/processos/$processoId'
      path: '/processos/$processoId'
      fullPath: '/processos/$processoId'
      preLoaderRoute: typeof ProcessosProcessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/$relatorioId': {
      id: '/relatorios/$relatorioId'
      path: '/relatorios/$relatorioId'
      fullPath: '/relatorios/$relatorioId'
      preLoaderRoute: typeof RelatoriosRelatorioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentosRoute: DocumentosRoute,
  PainelRoute: PainelRoute,
  UsuariosRoute: UsuariosRoute,
  ProcessosProcessoIdRoute: ProcessosProcessoIdRoute,
  RelatoriosRelatorioIdRoute: RelatoriosRelatorioIdRoute,
  ProcessosIndexRoute: ProcessosIndexRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
